/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.sudip.familytree;

import org.junit.Test;

public class FamilyTreeApplicationTest {
    @Test
    public void testAppHasAGreeting() {
        FamilyTreeApplication classUnderTest = new FamilyTreeApplication();
    }
}
